/**
 * Heatmap Calendar data file generator (v0.8.1).
 *
 * After every daily review writes its `## Today's habits status` section, we
 * walk back through the year's daily reviews per habit and emit a markdown
 * file at `🤖 AI/Habit-Data/<habit-id>.md` containing a `dataviewjs` codeblock
 * the Heatmap Calendar plugin renders. The user can embed that file in any
 * markdown note (`![[🤖 AI/Habit-Data/gym]]`) to surface a yearly heatmap.
 *
 * Format follows Heatmap Calendar's `renderHeatmapCalendar()` API: an entries
 * array of `{ date, intensity, content }` objects. We use intensity = 1 for
 * pass, 0.5 for uncertain, -1 for fail; cells with no entry render as the
 * plugin's default "empty" color.
 */

import { App, TFile } from "obsidian";
import { applyDatePlaceholders, todayISO, toISO } from "./paths";
import { Habit } from "./habits";

const HABIT_DATA_FOLDER = "🤖 AI/Habit-Data";

interface DayEntry {
  date: string;
  status: "pass" | "uncertain" | "fail";
  evidence?: string;
}

/**
 * For each active habit, scan daily reviews back to year-start, collect
 * pass/uncertain/fail entries, and write a Heatmap Calendar codeblock file.
 * Idempotent — overwrites the existing file each time.
 */
export async function writeHabitDataFiles(
  app: App,
  reviewsPathTemplate: string,
  habits: Habit[]
): Promise<void> {
  if (habits.length === 0) return;
  const today = todayISO();
  const yearStart = `${today.slice(0, 4)}-01-01`;
  const dates = enumerateDates(yearStart, today);

  // Read every daily review once (covers all habits in one pass).
  const reviewByDate = new Map<string, string>();
  for (const d of dates) {
    const path = applyDatePlaceholders(reviewsPathTemplate, d);
    const file = app.vault.getAbstractFileByPath(path);
    if (file instanceof TFile) {
      reviewByDate.set(d, await app.vault.read(file));
    }
  }

  await ensureFolder(app, HABIT_DATA_FOLDER);

  for (const h of habits) {
    const entries: DayEntry[] = [];
    for (const d of dates) {
      const content = reviewByDate.get(d);
      if (!content) continue;
      const status = parseHabitStatus(content, h.id);
      if (status) entries.push({ date: d, status });
    }
    const outPath = `${HABIT_DATA_FOLDER}/${h.id}.md`;
    const body = buildDataFile(h, entries, today.slice(0, 4));
    const existing = app.vault.getAbstractFileByPath(outPath);
    if (existing instanceof TFile) {
      await app.vault.modify(existing, body);
    } else {
      await app.vault.create(outPath, body);
    }
  }
}

function buildDataFile(habit: Habit, entries: DayEntry[], year: string): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`sb-generated: true`);
  lines.push(`sb-habit-id: ${habit.id}`);
  lines.push(`sb-year: ${year}`);
  lines.push(`sb-generated-at: ${new Date().toISOString()}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${habit.name} — ${year} heatmap`);
  lines.push("");
  lines.push(
    "_Auto-generated by Second Brain after each daily review. Don't edit — your changes will be overwritten._"
  );
  lines.push("");
  lines.push("```dataviewjs");
  lines.push(`// Heatmap Calendar plugin (Richardsl/heatmap-calendar-obsidian)`);
  lines.push(`// must be installed for this block to render.`);
  lines.push("const entries = [");
  for (const e of entries) {
    const intensity = e.status === "pass" ? 1 : e.status === "uncertain" ? 0.5 : -1;
    const content = e.status === "pass" ? "✓" : e.status === "fail" ? "✗" : "?";
    lines.push(
      `  { date: ${JSON.stringify(e.date)}, intensity: ${intensity}, content: ${JSON.stringify(content)} },`
    );
  }
  lines.push("];");
  lines.push("renderHeatmapCalendar(this.container, {");
  lines.push(`  year: ${year},`);
  lines.push(`  entries,`);
  lines.push(
    `  colors: { green: ["#1c4423", "#2d6a3a", "#3e9152", "#4fb86b"], red: ["#5c2323"], yellow: ["#5c4a23"] },`
  );
  lines.push("});");
  lines.push("```");
  return lines.join("\n");
}

function parseHabitStatus(
  content: string,
  habitId: string
): "pass" | "uncertain" | "fail" | null {
  const section = extractSection(content, "Today's habits status");
  if (!section) return null;
  const re = new RegExp(
    `^\\s*-\\s+(✅|⚠️|❌)\\s+${escapeRegex(habitId)}\\s*[—-]`,
    "m"
  );
  const m = section.match(re);
  if (!m) return null;
  return m[1] === "✅" ? "pass" : m[1] === "❌" ? "fail" : "uncertain";
}

function extractSection(content: string, header: string): string | null {
  const re = new RegExp(`^##\\s+${escapeRegex(header)}\\s*$`, "m");
  const m = content.match(re);
  if (!m || m.index === undefined) return null;
  const start = m.index + m[0].length;
  const nextHeader = content.slice(start).search(/^##\s+/m);
  return nextHeader < 0
    ? content.slice(start)
    : content.slice(start, start + nextHeader);
}

function enumerateDates(start: string, end: string): string[] {
  const out: string[] = [];
  const cur = new Date(start + "T00:00:00");
  const stop = new Date(end + "T00:00:00");
  while (cur <= stop) {
    out.push(toISO(cur));
    cur.setDate(cur.getDate() + 1);
  }
  return out;
}

async function ensureFolder(app: App, folderPath: string) {
  if (app.vault.getAbstractFileByPath(folderPath)) return;
  try {
    await app.vault.createFolder(folderPath);
  } catch {
    // Race; harmless.
  }
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
